### ISSUE TITLE
Managing an Akka Cluster on Kubernetes

### ISSUE THREAD

**Issue by magro** [reactive-systems-hamburg/reactive-systems-hamburg#3]
(proposal by @markusjura)

#### Description
Akka Cluster is a powerful toolkit for building distributed applications. But as always, power comes with a price. Special care needs to be taken during bootstrapping, network partitions and gracefully stopping a cluster.

In this talk, Markus introduces the Akka Management CoordinatedShutdown and Akka Split Brain Resolver modules and demonstrates on a running Kubernetes cluster how these libraries can help to manage an Akka Cluster in production. Join us when you want to know how a stateful application can handle rolling deployments without downtime and without losing in-flight requests and how it can safely recover from network partitions.

#### Bio
Markus is Scala Lead at MOIA. As a Scala enthusiast, his focus is to design and build distributed systems based on Akka. He is a very active member of the German Scala community, co-organizing hackathons and user groups in Hamburg and Berlin. Markus is also the co-founder and former CTO of Y-Combinator funded startup.

#### Date
Flexible starting from Mid August

**Comment by markusjura** [comment]
Talk on 15th of August 2018: https://www.meetup.com/Reactive-Systems-Hamburg/events/253002298/
