### ISSUE TITLE
Is there anybody out there?

### ISSUE THREAD

**Issue by markusjura** [reactive-systems-hamburg/reactive-systems-hamburg#4]
**Description**
Welcome to the world as seen through the eyes of a cluster node! In order to ensure fault-tolerance and scalability, reactive applications have no choice but to embrace distribution.
Unfortunately, this also means embracing the uncertainty and nondeterminism that comes with building networked applications:
changes in link quality, network partitions and outages of individual nodes are scenarios that need to be addressed first-hand when designing such systems. 

In this talk, you will learn about failure detectors, dissemination strategies, and consensus algorithms in the context of Akka Cluster, all interleaved with a healthy dose of Pink Floyd.

**Bio**
Manuel Bernhardt is a passionate engineer, author, speaker and consultant who has a keen interest in the science of building and operating networked applications that run smoothly despite their distributed nature. Since 2008, he has guided and trained enterprise teams on the transformation to distributed computing. In recent years he is focusing primarily on production systems that embrace the reactive application architecture, using Akka, Play Framework, Scala and Java to this end.

**Comment by lutzh** [comment]
https://www.meetup.com/de-DE/Reactive-Systems-Hamburg/events/253131828/
