### ISSUE TITLE
DIY Akka Persistence with FoundationDB

### ISSUE THREAD

**Issue by meln1k** [reactive-systems-hamburg/reactive-systems-hamburg#8]
**Description**
Akka Persistence is a commonly used library for building event-sourcing based applications. However, its default implementation, akka-persistence-cassandra has some limitations due to the nature of the Cassandra database. At the other side it is possible to overcome those limitations by choosing a database with better consistency guarantees and writing a plugin to support it. 

In this talk you will learn about akka-persistence and Cassandra, why this combination has several limitations, and how to build an akka-persistence plugin from scratch using FoundationDB which will not have the problems akka-persistence-cassandra has.

**Bio**
Nikita is Software Engineer at MOIA. Nikita is interested in distributed systems and data-intensive applications. His previous background includes building container orchestration platform at Mesosphere (now D2IQ) and building event-sourcing based backends at Zalando.

**Proposed date**
October/First half of November

**Comment by markusjura** [comment]
Checking with the organizers when to schedule the talk.

**Comment by markusjura** [comment]
Currently scheduled for 14.11 (in draft mode).
